### ISSUE TITLE
If execution fails, breaks table may not get dropped

### ISSUE THREAD

**Issue by katy-sadowski** [OHDSI/ClinicalCharacteristics#13]
Should add DROP IF EXISTS prior to the SELECT INTO queries in Step 1:
https://github.com/OHDSI/ClinicalCharacteristics/blob/6ac4deaf485a9cfb1f5bd3e52f01f47ed4dc2e20/R/conversion.R#L312-L322

**Comment by mdlavallee92** [comment]
ok added tempEmulationSchema in SqlRender::translate. This should drop it treating all tables as temp even in snowflake. Will close with PR to main
