### ISSUE TITLE
Error in makeClinChar

### ISSUE THREAD

**Issue by rfherrerac** [OHDSI/ClinicalCharacteristics#16]
When doing
analysisSettings <- makeClinChar(targetCohortIds = 1:5,
dbms = con@dbms,
targetCohortNames = executionSettings$databaseName,
cdmDatabaseSchema = executionSettings$cdmDatabaseSchema,
workDatabaseSchema = executionSettings$workDatabaseSchema,
cohortTable = executionSettings$cohortTable)

Got an error

Error in (function (cl, name, valueClass) :
assignment of an object of class “NULL” is not valid for @‘tempEmulationSchema’ in an object of class “executionSettings”; is(value, "character") is not TRUE

ClinicalCharacteristics version 0.2.9

**Comment by mdlavallee92** [comment]
tested on redshift when tempEmulationSchema is NULL should be good. Please give your example another try, let me know if it errors out again.
