### ISSUE TITLE
Add better docs for customBreaks

### ISSUE THREAD

**Issue by katy-sadowski** [OHDSI/ClinicalCharacteristics#17]
https://github.com/OHDSI/ClinicalCharacteristics/blob/6ac4deaf485a9cfb1f5bd3e52f01f47ed4dc2e20/R/conversion.R#L225-L243

The `cut` function is super confusing.  Took me a lot of trial and error to get this one to work correctly. Let's add a vignette with more description of how this function works and some examples.

**Comment by mdlavallee92** [comment]
updated as of v0.3.2.....likely to change with v1 sprint
