### ISSUE TITLE
Better coverage and examples for summarizing measurements

### ISSUE THREAD

**Issue by mdlavallee92** [OHDSI/ClinicalCharacteristics#18]
- Document how to summarize lab measurments as of today
- Draft ways to improve measurment summaries 
       - Summarize by ranges of values 
       - temporal values

@alondhe and @katy-sadowski anything to add on this?

**Comment by katy-sadowski** [comment]
some things i think would ideally be included (though realize it's hard):

- selection strategy when more than 1 measurement value w/in a time period (min? max? avg? latest? earliest?)
- selection strategy when more than 1 measurement value on same date (min? max? avg? ...)

**Comment by mdlavallee92** [comment]
closing due to v1 revamp...will address later
